'''Constantes do sistema SisCOV'''

TIPO_DE_ATIVIDADE = [
    "",
    "Reunião Comunitária",
    "Cadastro de Famílias",
    "Entrega de Notificações",
    "Diligências de Cartoriais",
    "Levantamento Fundiário",
    "Relatório Antropológico",
    "Levantamento de Dados",
    "Vistoria e Avaliação",
    "Georreferenciamento",
    "Visita Técnica",
    "Outros"
]

EMAILS = [
    '',
    'andrea.monteiro@incra.gov.br',
    'cosme.moura@incra.gov.br',
    'everaldo.costa@incra.gov.br',
    'francisco.rodrigues@incra.gov.br',
    'geandro.castro@incra.gov.br',
    'jennifer.almeida@incra.gov.br',
    'lidiane.amorim@incra.gov.br',
    'luana.ssantos.colaborador@incra.gov.br',
    'lucas.gariani@incra.gov.br',
    'mauricio.matos@incra.gov.br',
    'michael.cardoso@incra.gov.br',
    'nilza.silva@incra.gov.br',
    'rafael.moscoso@incra.gov.br',
    'rodrigo.alexandre@incra.gov.br',
    'rosangela.lima@incra.gov.br',
    'souhayl.ayoubi@incra.gov.br',
    'stefany.dornelas@incra.gov.br',
    'umberto.junior@incra.gov.br'
]

COMUNIDADES = [
    "Santa Joana",
    "Nova Esperança",
    "Jiquiri/São Raimundo",
    "Monge Belo",
    "Saco das Almas",
    "Santa Maria dos Pinheiros",
    "Finca Pé",
    "Aliança/Santa Joana",
    "Bacuri dos Pires",
    "Filipa",
    "Ipiranga do Carmina",
    "Jamary dos Pretos",
    "Santana dos Pretos",
    "Alto Bonito",
    "Boqueirão dos Vieiras",
    "Cutia/Santa Rita/Baiuna",
    "Estiva II/Beleza",
    "Matões dos Moreira",
    "Monte Alegre / Olho D'água dos Grilos",
    "Bolonha",
    "Santa Rita dos Matões",
    "Vila Nova de Ana Dias",
    "Outeiro",
    "Pitoró dos Pretos",
    "Maxixe",
    "Olho D'água/13 de Maio",
    "Preguiça",
    "Mata de São Benedito",
    "Mocambo/Mirim/Curitiba",
    "Curral Grande",
    "Mucambo",
    "Piqui/Santa Maria dos Pretos",
    "Rampa/Alto Alegre/Piqui",
    "Laranjeira/Boa Vista",
    "São Zacarias II",
    "Soledade",
    "Campo Grande",
    "Canta Galo",
    "Centro de Vovó",
    "Mutiti",
    "Samucangaua",
    "Santana",
    "Os Pretos de Bom Sucesso",
    "Santa Rosa dos Pretos",
    "Santa Cruz",
    "Árvore Verde",
    "Gapó",
    "Bom Jesus dos Pretos",
    "Nossa Senhora da Conceição / Recurso",
    "Camaputiua",
    "Centro dos Viola",
    "Cariongo",
    "Catucá",
    "Santo Antônio dos Pretos",
    "Piratininga",
    "Campo Redondo",
    "Guaraciaba",
    "Peixes",
    "Aranha",
    "Currupira",
    "Graça de Deus",
    "Juçaral",
    "Maiabi",
    "Oiteiro",
    "Paraíso",
    "Pedreiras",
    "Rio do Curral",
    "Santana dos Prazeres",
    "Santiago",
    "Vista Alegre",
    "Cipoal dos Pretos",
    "Mocorongo",
    "Jacarezinho",
    "Mimoco",
    "São Francisco/Malaquias",
    "Alcântara",
    "Damásio",
    "Guarimandiua",
    "Monte Cristo",
    "Mucambo",
    "Santo Antônio",
    "Amapá dos Catarino",
    "Mata Boi",
    "São José Fogoso",
    "Ilha das Pedras",
    "Sussego",
    "Tibiri",
    "Todos os Santos",
    "Barriguda/Anajá",
    "Marmorana/Boa Hora III",
    "Santarém/Santana",
    "São José",
    "Sumauma",
    "Lagoa do Caminho",
    "Rafael",
    "Turiaçu",
    "Estiva dos Cotós",
    "Belo Monte",
    "Bom Jesus/Santa Maria dos Moreiras",
    "Lacral/Espírito Santo",
    "São Benedito do Elcias",
    "Boa Vista",
    "Jussatuba",
    "Mata III",
    "Santana/São Patrício",
    "Tijuca",
    "Benfica",
    "Mandacarú dos Pretos",
    "Mata Virgem",
    "Outeiro dos Nogueiras",
    "Santa Helena",
    "Santo Antônio dos Pretos",
    "São Francisco",
    "São Raimundo Nonato",
    "Jaguarana",
    "Bem Fica/Olho d’Água dos Pimentas",
    "Pericumã/Ponta do Lago",
    "Pirinã",
    "Queimada de João",
    "Santa Rosa",
    "Sudário",
    "Belo Monte",
    "Pacoã",
    "Rio dos Peixes",
    "Santa Maria",
    "Buragir",
    "Javi",
    "Outeiro",
    "Ariquipá",
    "Vila Nova Ilha do Cajual",
    "Santa Maria",
    "Flechal",
    "Santa Bárbara dos Mafras",
    "Brasilina",
    "Boa Vista",
    "Estrela",
    "Santa Luzia",
    "Santa Maria dos Pinheiros",
    "São Miguel",
    "Juçaral",
    "Flores",
    "Zé Maria",
    "São João dos Campos",
    "Castelo",
    "Centro Grande de Maria",
    "Data Arraial",
    "Maria Madalena",
    "Igaruçu",
    "São Bartolomeu",
    "Papagaio",
    "Alto Bonito",
    "Sapucaial",
    "Bitiua",
    "Cruzeiro",
    "Enseada Grande",
    "Preguiça Velha",
    "São Pedro",
    "Recanto dos  Poetas",
    "Caranguejo",
    "Palestina",
    "Bom Jesus",
    "Curral de Vara",
    "Itapera",
    "João Luís",
    "Os Paulos",
    "Preguiça Nova",
    "Santa Izabel",
    "Santa Rita",
    "Tanque de Valença",
    "Alto da Pedra",
    "Jacareí dos Pretos",
    "Francisco Gonçalves Lisboa/Potó Velho",
    "Pedrinhas",
    "Potozinho",
    "São Domingos",
    "Conduru/Conceição/Bana Fogo/S.Benedito/Estopa",
    "São Francisco",
    "Joaquim Maria",
    "Charco",
    "Lagoa Grande",
    "Acre",
    "Boa Esperança dos Campos",
    "Boa Vista dos Freitas",
    "Brasília",
    "Cedro",
    "Centro dos Cruz/Bela Vista/Mutambal/Centro do Jaime e Bate Mão",
    "Fazenda Velha/Monte Cristo",
    "Frechal dos Campos",
    "Mata Burro/Santo Antônio dos Vieiras",
    "Morada Nova do Deusdeth",
    "Ponta na Região dos Campos",
    "Santa Filomena",
    "Santa Rosa",
    "Santarém",
    "Boa Hora do Puluca",
    "Barro Vermelho",
    "Boa Hora",
    "Engenho do Lago",
    "Estiva dos Mafras",
    "Monte Cristo",
    "Penteado",
    "Rio do Pau",
    "Rio Grande",
    "São José do Lugar",
    "São Roque",
    "Deserto",
    "Fleixeira",
    "Ramal do Quindiua",
    "Contendas",
    "Jacaré",
    "Mocajituba I",
    "São José",
    "Tubarão/Gleba Itamatatíua",
    "Santa Rosa",
    "Vila Fé em Deus",
    "Miranda do Rosário",
    "Santo Antônio dos Pretos",
    "Moreira",
    "São Benedito Barros",
    "Boca da Mata",
    "Pução",
    "São José do Brito",
    "Depósito",
    "Retiro",
    "Cambirimba",
    "Retiro/São João da Mata",
    "Jutay",
    "Paissandu",
    "Bandeira",
    "Janaubeira",
    "Pindoval de Fama",
    "Santa Barbára/Lagoa da Maria Rosa",
    "Lago do Coco",
    "Povoado Quebra Foice",
    "Funil",
    "Jacaré",
    "Monte Lindo II",
    "Cana Brava",
    "Caruaras",
    "Monte Cristo/Matuzinho",
    "Santa Bárbara",
    "Santo Antônio",
    "Capoeira de Gado",
    "Santa Luzia",
    "Vista Alegre",
    "Maranhão Novo",
    "Cacaueiro",
    "Canta Galo I",
    "Bacabal",
    "Boa Vista",
    "Boa Vista",
    "Bom Princípio",
    "Pau Pombo",
    "Pericaua",
    "São Raimundo",
    "Vera Cruz",
    "Caminho Novo",
    "Chapadinha 01",
    "Nazaré",
    "Rumo",
    "Santa Rosa",
    "Aldeia Velha",
    "Mó São Caetano",
    "Curva da Mangueira",
    "Engole",
    "Mafra",
    "Pericumã",
    "Mato Alagado I",
    "Munim Mirim",
    "Macajubal",
    "Porto de Cabeceira",
    "Bom que Dói",
    "Conceição",
    "Enseada dos Nogueiras",
    "Mondêgo",
    "Pericumã",
    "Santa Tereza",
    "Vivo",
    "Açude",
    "Boi de Carro",
    "Canavial",
    "Iteno",
    "São Roque",
    "Rio de Peixe",
    "Santa Rita",
    "Sumauma",
    "Armindio",
    "Onça",
    "Mariano dos Campos",
    "Boqueirão",
    "Canto do Lago",
    "Juraraitá",
    "Turimirim",
    "Carro Quebrado",
    "Monta Barro/Queimadas/Três Irmãos",
    "Gurutil/Baturité/Bom Viver",
    "Itamatatiua",
    "Queimadas",
    "Cana Brava das Moças",
    "Deus Bem Sabe/Paxibal",
    "Careminhas",
    "Angelim",
    "Pirinã",
    "São Domingos",
    "Santa Cruz I e II",
    "Estrela Divina",
    "São Bento/Data Genipapo",
    "Prata do Quirino",
    "Poço de Pedra",
    "Sibéria",
    "São Benedito do Caratíua",
    "Sapucaia do Albino",
    "Santa Rita dos Cardosos",
    "Santa Cruz",
    "São Roque",
    "São Bento",
    "Ilha de São José/Madureira",
    "Puraquê",
    "Oiteiro",
    "Alto Brasil/Boa Vista",
    "Cuba",
    "Condurus",
    "Soledade",
    "Mundico",
    "Tanque de Rodagem",
    "São Joaquim",
    "Mendes/Adjacência",
    "Curralzinho",
    "Brejo de São Felix/Acquib",
    "Cruzeiro",
    "Fortaleza",
    "Cachoeira",
    "Santa Rita",
    "Santa Luzia",
    "Capoeira Grande",
    "Bacuri",
    "Santa Filomena",
    "Monte Alegre",
    "São Francisco de Onório",
    "Guajará",
    "Imbiral/Cabeça Branca/São Benedito do Céu",
    "Coheb",
    "Promissão Velha",
    "Fandango",
    "São Pedro",
    "Campinho",
    "Lago Grande",
    "Boa Esperança",
    "Porto de Baixo",
    "São Bento",
    "São Benedito dos Colocados",
    "Malungos do Olho D'Água",
    "Lago do Sapateiro",
    "Santa Rita",
    "Mocajituba II",
    "Santo Antonio dos Mandingas",
    "Santa Cruz",
    "Lagoa do Leme",
    "Rio dos Peixes",
    "Sítio dos Arrudas",
    "Pedreiras",
    "São Lourenço/Unidos Venceremos",
    "Posto Seleção",
    "Picadas",
    "João Ganga",
    "Monteiro",
    "Rosário",
    "São José de Belino",
    "Maruim",
    "Nova Jericó",
    "Quimeira",
    "Cuba",
    "Boa Vista dos Conrados",
    "Cocalinho",
    "Guerreiro",
    "Dona Selvina do Povoado Tabuleiro",
    "São Marcos",
    "Centro Grande",
    "Burgos",
    "Ponta do Curral",
    "Queres",
    "Itaquipé",
    "São José",
    "Poleiro",
    "São José dos Matos",
    "Santa Rosa",
    "Malhadalta de Adão",
    "Santa Maria",
    "Cedreiro/Simaúma",
    "São José/Zé Bernardo",
    "Bom Jardim",
    "Ladeira",
    "Ilhas do Teso",
    "Centro do Isidório",
    "Cumbi",
    "Cupauba",
    "Guarimã",
    "São Cristóvão",
    "Tambá",
    "Barriguda/Magnifica/Pulgão/Campo Rio",
    "Proteção/São João do Povoado Mata",
    "Corrente II",
    "Sedreiro/Sumaúma",
    "Santa Vitória Gama",
    "Macacos/Brejim/Curupá",
    "Ponta Bonita",
    "Monte Alegre",
    "Paraíso/Anajazal",
    "São Domingos dos Pretos",
    "São Paulo Gama",
    "São Lourenço",
    "Alta Floresta",
    "Cedro",
    "Bom Descanso",
    "Vai Quem Quer/Boi Baiano/Vila Nova",
    "Curicas/Lagoa do Canto",
    "Lavras",
    "São João/Merengo",
    "Santo Antônio dos Coelhos",
    "Amapá dos Lucindos",
    "Cantinho",
    "Teso Grande",
    "Jacu",
    "Morro Redondo",
    "Santa Rosa do Barão",
    "Brejinho",
    "Achuí II",
    "Miritiba",
    "Guaribas",
    "Babaçual dos Pretos",
    "Vila Nova",
    "Cumum",
    "Nova Vila de São Raimundo",
    "Buqueirão do Salazar",
    "São Benedito",
    "Fazenda",
    "Barra da Tereza",
    "Andirobal",
    "Bacurizeiro",
    "Santa Maria",
    "Santo Antonio do Coco",
    "Assuntinga",
    "Alto Grande"
]

MUNICIPIOS = [
    '',
    'Açailândia',
    'Afonso Cunha',
    'Água Doce do Maranhão',
    'Alcântara',
    'Aldeias Altas',
    'Altamira do Maranhão',
    'Alto Alegre do Maranhão',
    'Alto Alegre do Pindaré',
    'Alto Parnaíba',
    'Amapá do Maranhão',
    'Amarante do Maranhão',
    'Anajatuba', 
    'Anapurus',
    'Apicum-Açu',
    'Araguanã',
    'Araioses',
    'Arame',
    'Arari',
    'Axixá',
    'Bacabal',
    'Bacabeira',
    'Bacuri',
    'Bacurituba',
    'Balsas',
    'Barão de Grajaú',
    'Barra do Corda',
    'Barreirinhas',
    'Bela Vista do Maranhão',
    'Belágua',
    'Benedito Leite',
    'Bequimão',
    'Bernardo do Mearim',
    'Boa Vista do Gurupi',
    'Bom Jardim',
    'Bom Jesus das Selvas',
    'Bom Lugar',
    'Brejo',
    'Brejo de Areia',
    'Buriti',
    'Buriti Bravo',
    'Buriticupu',
    'Buritirana',
    'Cachoeira Grande',
    'Cajapió',
    'Cajari',
    'Campestre do Maranhão',
    'Cândido Mendes',
    'Cantanhede',
    'Capinzal do Norte',
    'Carolina',
    'Carutapera',
    'Caxias',
    'Cedral',
    'Central do Maranhão',
    'Centro do Guilherme',
    'Centro Novo do Maranhão',
    'Chapadinha',
    'Cidelândia',
    'Codó',
    'Coelho Neto',
    'Colinas',
    'Conceição do Lago Açu',
    'Coroatá',
    'Cururupu',
    'Davinópolis',
    'Dom Pedro',
    'Duque Bacelar',
    'Esperantinópolis',
    'Estreito',
    'Feira Nova do Maranhão',
    'Fernando Falcão',
    'Formosa da Serra Negra',
    'Fortaleza dos Nogueiras',
    'Fortuna',
    'Godofredo Viana',
    'Gonçalves Dias',
    'Governador Archer',
    'Governador Edison Lobão',
    'Governador Eugênio Barros',
    'Governador Luiz Rocha',
    'Governador Newton Bello',
    'Governador Nunes Freire',
    'Graça Aranha',
    'Grajaú',
    'Guimarães',
    'Humberto de Campos',
    'Icatu',
    'Igarapé do Meio',
    'Igarapé Grande',
    'Imperatriz',
    'Itaipava do Grajaú',
    'Itapecuru-Mirim',
    'Itinga do Maranhão',
    'Jatobá',
    'Jenipapo dos Vieiras',
    'João Lisboa',
    'Joselândia',
    'Junco do Maranhão',
    'Lago da Pedra',
    'Lago do Junco',
    'Lago dos Rodrigues',
    'Lago Verde',
    'Lagoa do Mato',
    'Lagoa Grande do Maranhão',
    'Lajeado Novo',
    'Lima Campos',
    'Loreto',
    'Luís Domingues',
    'Magalhães de Almeida',
    'Maracaçumé',
    'Marajá do Sena',
    'Maranhãozinho',
    'Mata Roma',
    'Matinha',
    'Matões',
    'Matões do Norte',
    'Milagres do Maranhão',
    'Mirador',
    'Miranda do Norte',
    'Mirinzal',
    'Monção',
    'Montes Altos',
    'Morros',
    'Nina Rodrigues',
    'Nova Colinas',
    'Nova Iorque',
    'Nova Olinda do Maranhão',
    'Olho d´Água das Cunhãs',
    'Olinda Nova do Maranhão',
    'Paço do Lumiar',
    'Palmeirândia',
    'Paraibano',
    'Parnarama',
    'Passagem Franca',
    'Pastos Bons',
    'Paulino Neves',
    'Paulo Ramos',
    'Pedreiras',
    'Pedro do Rosário',
    'Penalva',
    'Peri Mirim',
    'Peritoró',
    'Pindaré-Mirim',
    'Pinheiro',
    'Pio XII',
    'Pirapemas',
    'Poção de Pedras',
    'Porto Franco',
    'Porto Rico do Maranhão',
    'Presidente Dutra',
    'Presidente Juscelino',
    'Presidente Médici',
    'Presidente Sarney',
    'Presidente Vargas',
    'Primeira Cruz',
    'Raposa',
    'Riachão',
    'Ribamar Fiquene',
    'Rosário',
    'Sambaíba',
    'Santa Filomena do Maranhão',
    'Santa Helena',
    'Santa Inês',
    'Santa Luzia',
    'Santa Luzia do Paruá',
    'Santa Quitéria do Maranhão',
    'Santa Rita',
    'Santana do Maranhão',
    'Santo Amaro do Maranhão',
    'Santo Antônio dos Lopes',
    'São Benedito do Rio Preto',
    'São Bento',
    'São Bernardo',
    'São Domingos do Azeitão',
    'São Domingos do Maranhão',
    'São Félix de Balsas',
    'São Francisco do Brejão',
    'São Francisco do Maranhão',
    'São João Batista',
    'São João do Carú',
    'São João do Paraíso',
    'São João do Soter',
    'São João dos Patos',
    'São José de Ribamar',
    'São José dos Basílios',
    'São Luís',
    'São Luís Gonzaga do MA',
    'São Mateus do MA',
    'São Pedro da Água Branca',
    'São Pedro dos Crentes',
    'São Raimundo das Mangabeiras',
    'São Raimundo do Doca Bezerra',
    'São Roberto',
    'São Vicente Ferrer',
    'Satubinha',
    'Senador Alexandre Costa',
    'Senador La Rocque',
    'Serrano do Maranhão',
    'Sítio Novo',
    'Sucupira do Norte',
    'Sucupira do Riachão',
    'Tasso Fragoso',
    'Timbiras',
    'Timon',
    'Trizidela do Vale',
    'Tufilândia',
    'Tuntum',
    'Turiaçu',
    'Turilândia',
    'Tutóia',
    'Urbano Santos',
    'Vargem Grande',
    'Viana',
    'Vila Nova dos Martírios',
    'Vitória do Mearim',
    'Vitorino Freire',
    'Zé Doca'
    ]
